# Question

This code snippet makes a fetch to get the first todo item from the JSON placeholder API. Or at least it tries to.

What is wrong with this code? 

Describe how async/await helps us avoid this mistake.

```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error('Fetch failed!');
    response.json();
  })
  .then(json => console.log(json))
  .catch(err => console.log(err))
```

You can run this code of course, but try not to! Try to figure out the issue on your own.

# Answer
The mistake here is that after the first '.then' does not return the response.json before chaining another '.then' statement. An async/await function accepts a url and options function which would allow other types of requests to be made. When the guard clause '(!response.ok)' is triggered, it will return an error and handle '4xx' and '5xx' responses in the catch block and treat them the same as errors thrown by fetch and response.json().
The code above can be refactored like so:
```jsx
const fetchData = async (url, options = {}) => {
  try {
    const response = await fetch(url, options);

    if (!response.ok) throw new Error(`Fetch failed.`)

    const json = await response.json();
    console.log(json);
  }
    catch (error) {
    
    console.error(error.message);
  }
}
```
# Teacher Feedback